### PR TITLE
READY FOR REVIEW - work around OpenSSL issue which mistakes a cert as self-signed if CA org == cert org

### LINKED ISSUE #808: Certificate verification failed against openssl from homebrew (1.0.2a-1)
Hello,

Depending on the version of openssl certificate verification of boot2docker failed, i don't know if this due to a bug in openssl or the way of boot2docker certificate has been generated, here is some log : 

```
➜  ~  openssl version
OpenSSL 0.9.8zc 15 Oct 2014
➜  ~  openssl s_client -CAfile /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/ca.pem -cert /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/cert.pem -key /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/key.pem -connect boot2docker:2376 -tls1 
CONNECTED(00000003)
depth=1 /O=Boot2Docker
verify return:1
depth=0 /O=Boot2Docker
verify return:1
```

```
➜  ~  /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2a 19 Mar 2015
➜  ~  /usr/local/opt/openssl/bin/openssl s_client -CAfile /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/ca.pem -cert /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/cert.pem -key /Users/joelwurtz/.boot2docker/certs/boot2docker-vm/key.pem -connect boot2docker:2376 -tls1

CONNECTED(00000003)
depth=0 O = Boot2Docker
verify error:num=18:self signed certificate
verify return:1
depth=0 O = Boot2Docker
verify error:num=21:unable to verify the first certificate
verify return:1
...

### PR DESCRIPTION
**Pull request by posita**
Fix #808 and SvenDowideit/generate_cert#10. Update `generate_cert` to 0.2 (to gain access to the `--org` command line option). Use `--org` command line option to ensure org for automatically-generated CA cert differs from org for automatically-generated client/server certs. Work-around for OpenSSL bug (see <http://tinyurl.com/pqgnb2a>).

Merge needed for (i.e., blocks):

* docker/compose#890
* docker/docker-py#465
* possibly others

--

The Author grants to the owners of this repository, and the owners of the software it contains known as "boot2docker" (the Software), as well as their heirs and assigns (the Recipients), a perpetual and transferable license to all rights the Author may have to any material submitted in this pull request as if it were created by the Recipients themselves. By merging this pull request, the Recipients agree to indemnify and hold harmless its Author against any harm or liability from its inclusion in the Software or use.

ALL MATERIALS IN THIS PULL REQUEST ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL ITS AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

### CODE REVIEW

**Comment by posita** [comment]
The reason this PR is submitted against this repository as opposed to [SvenDowideit/generate_cert](/SvenDowideit/generate_cert) is because @SvenDowideit [gently pointed out](/SvenDowideit/generate_cert/issues/10#issuecomment-129264119) that a patch to `generate_cert` is not needed to overcome the issue. Rather boot2docker can call it with the appropriate command line options when generating the certificates.

**Comment by SvenDowideit** [comment]
@tianon @icecrime @aanand @bfirsh can we add this for 1.8.0 boot2docker, or should I make a separate iso for user's that aren't going to move to docker-machine straight away.

**Comment by SvenDowideit** [comment]
LGTM

**Comment by bfirsh** [comment]
Looks like this is worth getting in for 1.8.

**Comment by aanand** [comment]
Agreed.

File: rootfs/rootfs/usr/local/etc/init.d/docker [hunk 1]
```diff
@@ -20,6 +20,9 @@ test -f '/var/lib/boot2docker/profile' && . '/var/lib/boot2docker/profile'
 : ${SERVERKEY:="${CERTDIR}serverkey.pem"}
 : ${CERT:="${CERTDIR}cert.pem"}
 : ${KEY:="${CERTDIR}key.pem"}
+: ${ORG:=Boot2Docker}
+: ${SERVERORG:="${ORG}"}
+: ${CAORG:="${ORG}CA"} # Append 'CA'; see <http://tinyurl.com/pqgnb2a>
```
Comment (tianon) [inline rootfs/rootfs/usr/local/etc/init.d/docker]: Can you please replace this tinyurl with the full `http://rt.openssl.org/Ticket/History.html?use
r=guest&pass=guest&id=3979` ?

**Comment by tianon** [comment]
Seems sane to me, and a simple enough change to include in 1.8 even so late in the game. :+1:

File: rootfs/rootfs/usr/local/etc/init.d/docker (hunk 1 above)
Comment (posita) [inline rootfs/rootfs/usr/local/etc/init.d/docker]: Done (and squashed).

**Comment by tianon** [comment]
Thanks :heart: 

LGTM
